---
- name: Setup new Ubuntu Home Server
  hosts: all
  become: true
  vars:
    username: anjimene
    nas_host: 192.168.1.71
    docker_group: docker
    uid_mount: 1001
    gid_mount: 995
    nas_mounts:
      - src: "//{{ nas_host }}/Data"
        dst: /media/data_storage
        fstype: cifs
        opts: "uid=1002,gid=1002,rw,vers=3.0,file_mode=0770,dir_mode=0770,credentials=/root/.smbcredentials"
      - src: "//{{ nas_host }}/Data/Cloud/nextcloud"
        dst: /media/cloud
        fstype: cifs
        opts: "rw,mfsymlinks,seal,uid=33,gid=0,file_mode=0770,dir_mode=0770,credentials=/root/.smbcredentials"
      - src: "//{{ nas_host }}/Data/Cloud/syncthing"
        dst: /media/syncthing
        fstype: cifs
        opts: "rw,mfsymlinks,seal,uid=33,gid=0,file_mode=0770,dir_mode=0770,credentials=/root/.smbcredentials"
      - src: "//{{ nas_host }}/Data/Reading"
        dst: /media/reading
        fstype: cifs
        opts: "nobrl,uid=1001,gid=995,rw,vers=3.0,file_mode=0770,dir_mode=0770,credentials=/root/.smbcredentials"
      - src: "//{{ nas_host }}/Data/Cloud/nextcloud/anjimene/files"
        dst: /media/anjimene
        fstype: cifs
        opts: "uid=1000,gid=1000,vers=3.0,file_mode=0770,dir_mode=0770,credentials=/root/.smbcredentials"
      - src: "UUID=8787724f-8f6d-4801-bf61-e4b916ed7a4b"
        dst: /media/usb
        fstype: auto
        opts: "nosuid,nodev,nofail,x-gvfs-show 0 0"
      - src: "/dev/disk/by-uuid/4EFF-A210"
        dst: /media/usb
        fstype: auto
        opts: "nosuid,nodev,nofail,x-gvfs-show 0 0"
      - src: "LABEL=KOBOeReader"
        dst: /media/kobo
        fstype: auto
        opts: "uid=1001,gid=995,nosuid,nodev,nofail,x-gvfs-show 0 0"

  tasks:
    - name: Add repo for mainline
      apt_repository:
        repo: 'ppa:cappelikan/ppa'
        state: present

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Upgrade all apt packages
      become: true
      apt:
        upgrade: dist

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Update apt and install required system packages
      apt:
        pkg:
          - apt-transport-https
          - net-tools
          - openssh-server
          - speedtest-cli
          - unzip
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - git
          - lm-sensors
          - cifs-utils
          - pkexec
          - mainline
          - linux-crashdump
          - hugo
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    # sudo groupadd docker
    - name: Create "docker" group
      group:
        name: "{{ docker_group }}"
        state: present

    # sudo usermod -aG docker root
    - name: Add user to "docker" group
      user:
        name: "{{ username }}"
        groups: "{{ docker_group }}"
        append: yes

    - name: Create credential file (used for fstab entry)
      copy:
        content: |
          username={{ username }}
          password={{ PWD_SMB_CREDENTIALS }}
        dest: /root/.smbcredentials
        mode: 0600
      become: true

    - name: create directory if they don't exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /media/anjimene
        - /media/cloud
        - /media/data_storage
        - /media/kobo
        - /media/reading
        - /media/syncthing
        - /media/usb
        - "/home/{{ username }}/docker"

    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Add mount to /etc/fstab
      lineinfile:
        path: '/etc/fstab'
        line: "{{ item.src }} {{ item.dst }} {{ item.fstype }} {{ item.opts }}"
      loop: "{{ nas_mounts }}"

    - name: mount all
      command: mount -a
      become: true
